apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus-container
          image: prom/prometheus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: saas
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 30s
        
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: [ "localhost:9090" ]
      
      - job_name: "saas-bff-service"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: [ "saas-bff-service" ]
      
      - job_name: "saas-oil-service"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: [ "saas-oil-service" ]

      - job_name: "saas-weather-service"
        static_configs:
          - targets: [ "saas-weather-service" ]
            
