apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-weather-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-weather
  template:
    metadata:
      labels:
        app: saas-weather
    spec:
      containers:
        - name: saas-weather-container
          image: yosigoon/saas-weather:saas-weather-application-release-dev_hyeongwon-6fb62e26e79b224ed0d4bf01cbd0f0a18a2c605c
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: saas-weather-service
spec:
  selector:
    app: saas-weather
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
