apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-application
  template:
    metadata:
      labels:
        app: spring-boot-application
    spec:
      containers:
        - name: spring-boot-container
          image: jaeholee1104/my_docker_hub:release-dev_jaeho-f75122ad55c478d8e5b46f4d82f344c0000a7741
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: docker-hub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort


