apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-bff-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-bff-application
  template:
    metadata:
      labels:
        app: saas-bff-application
    spec:
      containers:
        - name: saas-bff-container
          image: jaeholee1104/saas-bff:release-dev_jaeho-f1d78fb4c66ef1e8904886f1d105bdeecef72b07
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: saas-bff-service
spec:
  selector:
    app: ssaas-bff-application
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5001
  type: LoadBalancer


