apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jaeho.lee@bespinglobal.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: jaeho.lee@bespinglobal.com
            apiKeySecretRef:
              name: cloudflare-api-key
              key: api-key
