apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-application
  template:
    metadata:
      labels:
        app: grafana-application
    spec:
      containers:
        - name: grafana-container
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "1234" # Grafana admin password
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
