apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-weather-deployment
  namespace: saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-weather-deployment
  template:
    metadata:
      labels:
        app: saas-weather-deployment
    spec:
      containers:
        - name: saas-weather-container
          image: jaeholee1104/saas-weather:release-develop-c8595a0c75adbb7cddcfe99e023aaebd9eea4d80
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: saas-weather-service
  namespace: saas
spec:
  selector:
    app: ssaas-weather-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
  type: NodePort


