apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: tempo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo-container
          image: grafana/tempo:latest
          ports:
            - containerPort: 3200
          volumeMounts:
            - name: tempo-storage
              mountPath: /var/tempo
          env:
            - name: TEMPO_CONFIG
              value: |
                server:
                  http_listen_port: 3200
                storage:
                  trace:
                    backend: local
                    local:
                      path: /Users/jaeho.lee/workspace/test
      volumes:
        - name: tempo-storage
          hostPath:
            path: /mnt/data/tempo
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: tempo-service
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3200









