apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: tempo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo-container
          image: grafana/tempo:latest
          ports:
            - containerPort: 3200
          env:
            - name: STORAGE_TYPE
              value: loki
            - name: STORAGE_CONFIG
              value: |
                loki:
                  url: http://loki-service.monitoring.svc.cluster.local:3100/loki/api/v1/push
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: tempo-service
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3200
